[pytest]
; Uncomment the following lines to enable headless browser runs, parallel execution, and self-contained HTML report generation by default
; addopts =  -n 3 --headless --html=reports/Report.html --self-contained-html